### ISSUE TITLE
Name question: isn't it Matador?

### ISSUE THREAD

**Issue by SpacyRicochet** [jeroensmeets/mastodon-app#42]
The README didn't make it completely if you did this on purpose, but the profession where someone fights a bull (or other bovine) is called a [matador](https://nl.wikipedia.org/wiki/Matador_(beroep)), not a matodor. 

Just wondering if it was on purpose.

**Comment by jeroensmeets** [comment]
You're completely right, and I'll update the README te explain more clearly why I named this app Matodor (it's using the vowels from Mastodon).

`Every mastodon needs a matador to tame it. I liked the idea of using the vowels (a-o-o) in the word Mastodon. That's why the app is called Matodor, it's not a typo ;-)`

**Comment by jeroensmeets** [comment]
changed in version 1.0.7

**Comment by SpacyRicochet** [comment]
Great stuff! I love how the byline for Matodor can be 'not a typo'

"Matodor; not a typo."
"Vlad; not a vampire."
