### ISSUE TITLE
Wish: push notifications

### ISSUE THREAD

**Issue by jeroensmeets** [jeroensmeets/mastodon-app#8]

**Comment by Gargron** [comment]
Likely not possible (GNU social hasn't got it either), since your app can't know in advance which domain it will need to connect to, and all of these push engines require pre-registration of the app with the provider... (If there *is* a way, let me know)

Potentially an alternative: https://github.com/Gargron/mastodon/issues/331 Although obviously websockets connections are worse on the battery and with a bad network than native push events from the android/iOS system...

**Comment by jeroensmeets** [comment]
@Gargron yes, have been thinking about setting up my own Mastodon instance esp. for this app, that could read the public timeline and generate notifications. Or maybe just setting up a script that reads the public timeline and generates push messages for each mention? In any case, that would ignore the new follower notification.

**Comment by puphime** [comment]
would suggest having the app run in the background, check for new interactions for the user periodically & display notifications, not necessarily push. would be very useful. mind you i'm not experienced in android dev and don't know if i'm making any sense

**Comment by Tschaul** [comment]
I'm guessing it runs in a chrome web view. Then this should help: https://developers.google.com/web/fundamentals/getting-started/codelabs/push-notifications/ 

The server/instance has to support it however by running the "companion" part of the example.

**Comment by jeroensmeets** [comment]
@Tschaul 11t doesn't run in a chrome webview.
